    ## MSG 
  - name: Stop Omnia MSG Servers
    shell: "{{ item }}"
    with_items: 
      - $JBOSS_HOME/bin/jboss-cli.sh --connect <<EOF
      - :shutdown(timeout=60)
      - exit
      - EOF
      - service activemq stop
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] == "6"
    become: yes
    become_method: su
    become_exe: "sudo su -"


    ## WEB
  - name: Stop Omnia WEB Servers
    shell: "{{ item }}"
    with_items: 
      - $JBOSS_HOME/bin/jboss-cli.sh --connect <<EOF
      - :shutdown(timeout=60)
      - exit
      - EOF
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] == "6"
    become: yes
    become_method: su
    become_exe: "sudo su -"