  - debug:
      msg: "Starting linux-patch-script-1"
  
  - name: 01 - Yum clean metadata
    command: yum clean metadata
    args:
      warn: no

  - name: 02 - Old CF output file for same of handover
    shell: rpm -qa --queryformat "%{NAME};%{VERSION}-%{RELEASE}\n" | sort -t\; -k 1 > /tmp/yum-Installed-pre.txt

  - name: 03 - Set variable to number of installed packages and available updates
    shell: "{{ item }}"
    with_items: 
      - export pre_pkg_inst=$(yum list installed | grep '^[a-Z0-9]' | wc -l)
      - export pre_pkg_avail=$(yum check-update --quiet | grep '^[a-Z0-9]' | wc -l)
      - echo -n "${HOSTNAME};${pre_pkg_inst};${pre_pkg_avail};" > /tmp/$HOSTNAME-yum-install.txt

  - name: 04 - Run yum update and output details
    yum:
      name: '*'
      state: latest
    register: yumoutput
    
  - name: 05 - Show registered var contents and structure
    debug:
      var: yumoutput

  - name: 06 - Copy the output to a local file
    copy:
      content: "{{ yumoutput | to_nice_yaml(indent=2) }}"
      dest: "/tmp/yum-update.txt"

  - name: 07 - Reboot machine after update
    reboot:
      msg: Reboot initiated by Ansible after patching
      post_reboot_delay: 30
      reboot_timeout: 600
      
  - mail: send email to infra once patching complete
      host: smtp.mail.yahoo
      port: 587
      username: frazmahmud78@yahoo.com
      password: TestPassword!23
      to: fraz.mahmud@mtcgroup.org.uk
      subject: Linux script 1 completed
      body: Script 1 has completed successfully. Check logs for more information. 
    ignore_errors: yes
    delegate_to: localhost
