- 
  name: Linux monthly patching 
  hosts: all
  serial: 2
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/script_1.yml
  - include: tasks/script_2.yml
  
  - mail: send email to infra once patching complete 
      to: infrastructureteam@mtcgroup.org.uk
      subject: Linux patching completed
      body: All patching has completed successfully. Check logs for more information. 
    ignore_errors: yes
