- 
  name: Linux monthly patching 
  hosts: all
  serial: 2
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/script_1.yml
  - include: tasks/script_2.yml
  - mail:
      host: localhost
      from: MGMT-EKS (AWX Ansible Patching Report)
      port: 25
      to: Infrastructure Team <fraz.mahmud@mtcgroup.org.uk>
      subject: '{{ tags.Name }}'
      body: Patching completed. Please find reports attached.
      attach: 
        - /tmp/yum-Installed-pre.txt
        - /tmp/$HOSTNAME-yum-install.txt
        - /tmp/yum-update.txt
        - /tmp/yum-Installed-post.txt
        - /tmp/$HOSTNAME-yum-install.txt
        - /tmp/post-yum-update.txt
    ignore_errors: yes
    delegate_to: localhost
