- 
  name: Linux monthly patching 
  hosts: all
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/script_1.yml
  - include: tasks/script_2.yml
  - mail:
      host: localhost
      from: MGMT-EKS (AWX Ansible Patching Report)
      port: 25
      to: Infrastructure Team <fraz.mahmud@mtcgroup.org.uk>
      subject: '{{ tags.Name }}'
      body: Patching completed. Please find reports attached.
      attach: 
        - /home/yum-Installed-pre.txt
        - /home/{{ tags.Name }}-yum-install.txt
        - /home/yum-update.txt
        - /home/yum-Installed-post.txt
        - /home/{{ tags.Name }}-yum-install.txt
        - /home/post-yum-update.txt
    ignore_errors: yes
