- 
  name: Linux monthly patching 
  hosts: all
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/script_1.yml
  - include: tasks/script_2.yml
  - mail:
      host: localhost
      from: MGMT-EKS (AWX Ansible Patching Report)
      port: 25
      to: Infrastructure Team <infrastructureteam@mtcgroup.org.uk>
      subject: '{{ tags.Name }}' '{{ private_ip_address }}'
      body: Patching completed. Please find reports attached.
      attach: 
        - /var/log/ansible-templates/yum-Installed-pre.txt
        - /var/log/ansible-templates/{{ private_dns_name }}-yum-install.txt
        - /var/log/ansible-templates/yum-update.txt
        - /var/log/ansible-templates/yum-Installed-post.txt
        - /var/log/ansible-templates/{{ private_dns_name }}-post-yum-install.txt
        - /var/log/ansible-templates/post-yum-update.txt
    ignore_errors: yes
