---
- hosts: all
  become: yes
  tasks:
  
  - name: 01 - Clear default repos added after kernel update and clear cache repo data
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
      - rm /etc/yum.repos.d/amzn-*.repo
      - rm /etc/yum.repos.d/epel.repo.rpmnew
      - rm /etc/yum.repos.d/epel-testing.repo

  - user:
      name: jsmith
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/jsmith_rsa

  - mail:
      host: localhost
      port: 25
      to: Infra Team <infrastructureteam@mtcgroup.org.uk>
      subject: Ansible-report
      body: 'System {{ ansible_hostname }} has been successfully provisioned.'
    ignore_errors: yes