---
- hosts: all
  become: yes
  tasks:
  
  - name: 01 - Clear default repos added after kernel update and clear cache repo data
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
      - rm /etc/yum.repos.d/amzn-*.repo
      - rm /etc/yum.repos.d/epel.repo.rpmnew
      - rm /etc/yum.repos.d/epel-testing.repo

  - user:
      name: jsmith
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/jsmith_rsa

  - name: 04 - Run yum update and output details
    yum:
      name: '*'
      state: latest
    register: yumoutput
    
  - name: 05 - Show registered var contents and structure
    debug:
      var: yumoutput

  - name: 06 - Copy the output to a local file
    copy:
      content: "{{ yumoutput | to_nice_yaml(indent=2) }}"
      dest: "/tmp/yum-update.txt"

  - mail:
      host: localhost
      from: MGMT-EKS (AWX Ansible)
      port: 25
      to: Infrastructure Team <infrastructreteam@mtcgroup.org.uk>
      subject: Ansible-report - Linux Patching Completed
      body: Linux patching completed. Please find reports attached.
      attach: /tmp/yum-update.txt
    ignore_errors: yes