---
- hosts: all
  become: yes
  tasks:
  
  - name: 01 - Clear default repos added after kernel update and clear cache repo data
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
      - rm /etc/yum.repos.d/amzn-*.repo
      - rm /etc/yum.repos.d/epel.repo.rpmnew
      - rm /etc/yum.repos.d/epel-testing.repo
    register: remove
    
  - debug:
      msg: "{{ ansible_play_hosts | map('extract', hostvars, 'remove') | map(attribute='stdout') | list }}"
    run_once: yes
  
  - name: 06 - Copy the output to a local file
    copy:
      content: "{{ remove | to_nice_yaml(indent=2) }}"
      dest: "/tmp/remove.txt"

  # - user:
  #     name: jsmith
  #     generate_ssh_key: yes
  #     ssh_key_bits: 2048
  #     ssh_key_file: .ssh/jsmith_rsa

  # - name: 04 - Run yum update and output details
  #   yum:
  #     name: '*'
  #     state: latest
  #   register: yumoutput
    
  # - debug:
  #     msg: "{{ ansible_play_hosts | map('extract', hostvars, 'yumoutput') | map(attribute='stdout_lines') | list }}"
  #   run_once: yes 

  # - name: 05 - Show registered var contents and structure
  #   debug:
  #     var: yumoutput

  # - name: 06 - Copy the output to a local file
  #   copy:
  #     content: "{{ yumoutput | to_nice_yaml(indent=2) }}"
  #     dest: "/tmp/yum-update.txt"

  # - name: 06 - Copy the output to a local file
  #   copy:
  #     content: "{{ yumoutput }}"
  #     dest: "/tmp/yum-update.txt"

  - shell: date
    register: date_res
    changed_when: false
  
  - debug:
      msg: "{{ ansible_play_hosts | map('extract', hostvars, 'date_res') | map(attribute='stdout') | list }}"
    run_once: yes

  - name: 06 - Copy the output to a local file
    copy:
      content: "{{ date_res | to_nice_yaml(indent=2) }}"
      dest: "/tmp/date_res.txt"

  - mail:
      host: localhost
      from: MGMT-EKS (AWX Ansible)
      port: 25
      to: Infrastructure Team <fraz.mahmud@mtcgroup.org.uk>
      subject: Ansible-report - Linux Patching Completed
      body: Linux patching completed. Please find reports attached.
      attach: 
      - /tmp/date_res.txt 
      - /tmp/remove.txt
    ignore_errors: yes