---
- hosts: all
  become: yes
  tasks:

  - mail:
      host: localhost
      from: MGMT-EKS (AWX Ansible)
      port: 25
      to: Infrastructure Team <fraz.mahmud@mtcgroup.org.uk>
      subject: "{{ ansible_hostname }}" - Linux Patching Report
      body: Linux patching completed. Please find reports attached.
      # attach: 
      #   - /tmp/remove.txt
    ignore_errors: yes